name: Workflow Кованого дракона

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    NEXT_PUBLIC_PHOTO_API: ${{ secrets.NEXT_PUBLIC_PHOTO_API }}
    NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

jobs:
    build:
        runs-on: ubuntu-latest # Используем стандартный runner от GitHub
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.16.0"

            - name: Установка pnpm
              run: npm install -g pnpm

            - name: Установка зависимостей
              run: pnpm install

            # Сборка и экспорт статического сайта
            - name: Сборка и экспорт статического сайта
              run: pnpm build

            - name: Деплой по FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.FTP_HOST }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./out/
                  server-dir: public_html/
